### ISSUE TITLE
Windows Backslash Directory Separator

### ISSUE THREAD

**Issue by JoelGaechter** [datahaki/bridge#32]
Windows uses backslash as its default directory separator. This can cause issues when writing a file to a string, e.g., using `File::toString` and then trying to read it again using, e.g., using `File::new`,  such as done in `FileFielWrap`, since backslash is a special character when interpreting strings.

Potential fixes could be:
- replacing backslash with double backslashes
- replacing backslash with forwardslash, which is recognised by `File::new`

**Comment by datahaki** [comment]
implemented here:

https://github.com/datahaki/bridge/pull/31/commits/40cd0022123d0b7c1707f0c0fa99009882c150ba

if not urgent, we will deploy update 2 weeks from now

**Comment by datahaki** [comment]
modified implementation here:

https://github.com/datahaki/bridge/pull/31/commits/4030f027c0409d84c89369edf792c8b929ab38a1

the current version uses the original java code from `Properties` and exports the key-values in the same order as they are visited by the `ObjectFieldsVisitor`
