### ISSUE TITLE
DatasetFactory Quantity Handling

### ISSUE THREAD

**Issue by JoelGaechter** [datahaki/bridge#33]
`DatasetFactory`uses `Scalar::number` in several places. If the `Scalar` is a `Quantity` this causes a crash.
In `DatasetFactory::xySeriesCollection` this seems to be taken care of but not elsewhere.

**Comment by datahaki** [comment]
please add a simple example that crashes so that it can be fixed.

**Comment by datahaki** [comment]
resolved here
https://github.com/datahaki/bridge/pull/31/commits/408c25cd6babf3d3e9802e5e760f217fe2a1b2c1
